### ISSUE TITLE
Installable and Publish?

### ISSUE THREAD

**Issue by ekristen** [PoorBillionaire/Windows-Prefetch-Parser#2]
It would be nice to see this published to the python package server and make install-able by creating a setup.py file?

**Comment by PoorBillionaire** [comment]
Thanks, I agree completely. It's something I need to do with all of my projects. I'll start working on this one first.

**Comment by ekristen** [comment]
Thanks. We are looking at including a few of your tools into the SIFT workstation https://github.com/sans-dfir/sift, and making this install-able will definitely help get that done.

**Comment by PoorBillionaire** [comment]
Apologies for the late reply, I'll have this done within the next couple of days. Recently my time has been saturated by refactoring the script - it was a bit bloated.

I have however moved the documentation to reStructuredText in preparation for PyPI submission.

**Comment by PoorBillionaire** [comment]
Alright, this script is now installable via setup.py. I also submitted it to PyPI to be installed via pip if desired. It's name in PyPI is 'windowsprefetch' - but the script itself still goes by 'prefetch.py'

Please let me know if you encounter difficulties!

**Comment by ekristen** [comment]
It has been added to the SIFT dev branch, after I finish making the latest updates it'll make its way into the master build, many thanks. https://github.com/sans-dfir/sift-bootstrap/commit/016b1f3cdf95aa29edf134c0ff36603c28d78811
